BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Auth_Tokens" (
	"Id"	INTEGER NOT NULL,
	"Selector"	TEXT,
	"Token"	TEXT,
	"UserId"	INTEGER NOT NULL,
	"Expires"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
